language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - ${NVM_PATH}_modules
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: nbHKwpZTEyJ2NcmGa540xThwMS1d7k7ZvCJErYyDTRP7SAb272iDjh/8EUgIzAurpxZRIiMHbUyN3CJwqmbo5iaFdz56gTA5E2Rs6/CXtjEtRAMOtgKLnTvlt7Ja40Hi7YtLFAMK9IKPXJlv1PKbJJ4jt+2V7Ge5TuFnybOwvs8fCndDfo9UbAGQaMbGkrmPBkWr+oj/eo4ZpKP2gY1srJeJnLdKG/wu2rgj8ix3ytc7N68S00tgu+QcucNsSRLe43q3YU609UwQvQQTft58mJqbCrgxYf92nc3Y7/j+JxvFShdMsAoW4IPV0GEuP4A4+VnkJkqW6ASWVeUdmoSHgq58inKSO63VAvwqHhWZPvs47JXaGLCyUhsmfcud88yfjdjAsJgVls5oQbvTT0nvWDLV6gdDXmHmbGB3mWpnrTX700bWm0ZS7PXOG/eLk/XjV+1ALtpBftRFF2YyNLG7LxJrUUj+320MqZlI5J2dXIsn1/6OivxrNdatitdtnN6IzIi0ORZMVO6ETfUq9BL0niGE0kzNQ0vD9UueiqK81bQHemFmVOL8ofXrgCpBjOdB/NzSUAYRXNayZFcyitafS5eXWO897z8zqntHo6nWjS1fK+auC9SdYWxMxDucLLMUx4LHJO5Eh0Y+S8B4vk1o30cQHN6xtWPOIN2jjaYBkxU=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
script: echo "Deploying!"
before_deploy: npm run build
deploy:
- provider: firebase
  skip_cleanup: false
  on:
    branch: master
  project: hoverboard-master
  token:
    secure: igoBu7h0tvPejmWwVt/OiEI2NyGJC0uTUg5RgCBMFpr88BvcclH8dPry78RrOKh1nRFZZC/ZrJ94TCQ8T7oP4Qd5c7TFojaoKAzvl2fAdXmuq+q/OlrRXR3Ee/4M7+np5P66L0h7r/TQynck5KVX4cgCY2RjHFT15JebQsFqxS9tW9FKcBChBGhPZqkloZDwKQqWP0ZupLtW2PQtyzaqQLoNfnhNoWzflIzX5YhIkNNY8t1kmSzjSVUnL1cUhj1DQS02UIpRCyZDDfsNMyP30mnh1w8ZJdSflB0VIx7O0nusUXHa5dw4ojLWBie8dk6K7xxQHt5SK1S8k3fbP1ez+Bw3L6Z/OlG/TC8zHXqxP7u/3lA1G15lv883PGJ98aak4aSKJymKYQQZqGXGKea8P3AQMINxFBn98ceGaPIsUXsYPFMBoXlt64Pt342b/RhhDRIlbvJU7j9B3gJ/lNdUCmsgWGIIZDGcgw4hd4pFgr4cF2B8JNcaz4miYOav6KNSB2IPQafFTFbavlThnjluVEschQoxb6IKpaVEk3sosEubkk9j4Z5/QlRNcf00tHIVzNut7r8FnRuB91KwpKPKP6Uwnk/Yl+QFXNRn7v33cY20tUHgZjwwwvJSgQDmggBdy+PxZLRDVlw2JR5pPqjseHjzJGmiAUJeytqmFw57xo4=
- provider: firebase
  skip_cleanup: true
